language: php
php:
- 7.2
before_script:
- composer install
script: make test-CI
after_script:
- wget https://scrutinizer-ci.com/ocular.phar;
- php ocular.phar code-coverage:upload --format=php-clover coverage.clover;